# Generated by Django 3.2.13 on 2022-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=30)),
                ('pageCount', models.IntegerField(default=0)),
                ('thumbnailUrl', models.CharField(max_length=256, null=True)),
                ('shortDescription', models.CharField(max_length=256, null=True)),
                ('longDescription', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default=True, max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
